modLoader = "javafml" #mandatory
loaderVersion = "47" #mandatory
license = "Creative Commons"
issueTrackerURL = "${git_url}/issues" #optional
[[mods]] #mandatory
modId = "exnihilomekanism" #mandatory
version = "5.0.0" #mandatory
displayName = "Ex Nihilo: Sequentia - Mekanism Addon" #mandatory
displayURL = "${curseforge_url}" #optional
logoFile = "logo.png" #optional
credits = "" #optional
authors = "NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
    An addon for Ex Nihilo: Sequentia that adds support for Mekanism.
    '''
[[dependencies.exnihilomekanism]]
modId = "exnihilosequentia"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihilomekanism]]
modId = "novacore"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihilomekanism]]
modId = "mekanism"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
