modLoader = "javafml" #mandatory
loaderVersion = "${loader_version}" #mandatory
license = "Creative Commons"
issueTrackerURL = "${git_url}/issues" #optional
[[mods]] #mandatory
modId = "exnihilomekanism" #mandatory
version = "${mod_version}" #mandatory
displayName = "Ex Nihilo: Sequentia - Mekanism Addon" #mandatory
displayURL = "${curseforge_url}" #optional
logoFile = "logo.png" #optional
credits = "" #optional
authors = "NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
    An addon for Ex Nihilo: Sequentia that adds support for Mekanism.
    '''
[[dependencies.exnihilomekanism]]
modId = "exnihilosequentia"
mandatory = true
versionRange = "${exnihilo_range}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihilomekanism]]
modId = "novacore"
mandatory = true
versionRange = "${nova_core_range}"
ordering = "AFTER"
side = "BOTH"
[[dependencies.exnihilomekanism]]
modId = "mekanism"
mandatory = true
versionRange = "${mekanism_range}"
ordering = "AFTER"
side = "BOTH"
