modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/NovaMachina-Mods/ExNihiloMekanism/issues"
license="CC BY-NC-SA 4.0"

[[mods]]
    modId="exnihilomekanism"
    logoFile="logo.png"
    version="1.0.0"
    displayName="Ex Nihilo: Sequentia - Mekanim Addon"
    updateJSONURL="https://api.modrinth.com/updates/3MbBTiGC/forge_updates.json"
    authors="NovaMachina"
    description='''Addon for Ex Nihilo: Sequentia to add support for Mekanism'''

[[dependencies.exnihilomekanism]]
    modId="neoforge"
    type="required"
    versionRange="[20.4, 21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnihilomekanism]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exnihilomekanism]]
   modId="exnihilosequentia"
   type="required"
   ordering="AFTER"
   side="BOTH"
   versionRange="[6.0.0, 7.0.0)"

[[dependencies.exnihilomekanism]]
   modId="mekanism"
   type="required"
   ordering="AFTER"
   side="BOTH"
   versionRange="[10.5.8, 10.6.0)"

